# Generated by Django 4.2.7 on 2025-11-23 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('meta_description', models.CharField(blank=True, max_length=150)),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_keywords', models.JSONField(blank=True, default=list, help_text='List of SEO keywords')),
                ('summary', models.TextField(blank=True, help_text='AI-generated summary of the post')),
                ('category', models.CharField(blank=True, help_text='AI-suggested category', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list, help_text='AI-suggested tags (list)')),
                ('embedding', models.JSONField(blank=True, default=list, help_text='Vector embedding for semantic search', null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='blog_post_created_45f0c6_idx'), models.Index(fields=['slug'], name='blog_post_slug_cdb902_idx')],
            },
        ),
    ]
