# Generated by Django 4.2.29 on 2026-05-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_userprofile_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('like', 'Like'), ('bookmark', 'Bookmark'), ('system', 'System'), ('comment_removed', 'Comment Removed')], default='system', max_length=20),
        ),
    ]
