# Generated by Django 4.2.29 on 2026-05-02 11:46

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_add_comment_removed_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_covers/', validators=[blog.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='post_gallery/', validators=[blog.validators.validate_image_upload]),
        ),
    ]
